### ISSUE TITLE
Does CFN keep the task def revision? 

### ISSUE THREAD

**Issue by pydevops** [awslabs/ecs-refarch-continuous-deployment#1]
If it doesn't, how does the CICD pipeline rollback to a previous revision if the deployment failed? 

Thanks!

**Comment by jpignata** [comment]
CloudFormation will wait for ECS to complete the deployment of the new task definition revision onto the service before cleaning up the old task definition revision. If you'd rather CloudFormation retain these revisions for later manual rollback, you can set an [UpdatePolicy](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html) on the TaskDefinition resource to Retain.

Hope that helps!

**Comment by taraspos** [comment]
Hey, @jpignata are you sure that `UpdatePolicy` can be set to `Retain` for TaskDefinition resource?
`DeletePolicy` could, but it works only if stack deleted, but I couldn't find a way to set `UpdatePolicy`. Also, doc says:
> Use the UpdatePolicy attribute to specify how AWS CloudFormation handles updates to the AWS::AutoScaling::AutoScalingGroup or AWS::Lambda::Alias resource.

**Comment by jpignata** [comment]
You're right, no. I'm not sure what January 2017 me was thinking, but I don't think an UpdatePolicy would work here. I'd be curious to test a `DeletionPolicy` on the `TaskDefinition` resource to see if that would retain older task definition versions. Since we're not using CloudFormation to drive the deployment this question is largely moot. The native CodePipeline -> ECS integration will retain older task definitions as inactive revisions in the current implementation of this reference architecture.

**Comment by irgeek** [comment]
I've just tested and can confirm that setting `DeletionPolicy: Retain` on the `AWS::ECS::TaskDefinition` resource _does not_ cause it to retain old revisions during the post-update cleanup phase.

**Comment by Tehnix** [comment]
Did anyone ever managed to keep around the task definitions? Even if it's just a hacky solution, we'd be interested in hearing :)

**Comment by taraspos** [comment]
AWS just released [UpdateReplacePolicy Attribute](https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html) which does exactly what we need :) 

Basically `UpdateReplacePolicy: Retain` does the trick.

**Comment by markotitel** [comment]
> AWS just released [UpdateReplacePolicy Attribute](https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html) which does exactly what we need :)
> 
> Basically `UpdateReplacePolicy: Retain` does the trick.

This is not supported for `AWS::ECS::TaskDefinition`. How did you test this?

> [UpdateReplacePolicy] is not permitted)

**Comment by taraspos** [comment]
@markotitel it works for me with the template like:
```yml
  ECSTask:
    Type: AWS::ECS::TaskDefinition
    UpdateReplacePolicy: Retain
    ...
```
<img width="717" alt="Screen Shot 2021-01-19 at 1 59 07 PM" src="https://user-images.githubusercontent.com/9948629/105031876-9816f880-5a5e-11eb-96f6-5b4c42bd246a.png">

**Comment by markotitel** [comment]
Getting back to confirm. It is working. @Trane9991
