### ISSUE TITLE
Failed deploying on Tokyo region

### ISSUE THREAD

**Issue by tech-a-go-go** [awslabs/ecs-refarch-continuous-deployment#12]
Failed deploying on Tokyo region due to the following error while creating VPC with cloudformation.

10:36:24 UTC+0900 CREATE_FAILED	AWS::EC2::Subnet	Subnet2	Value (ap-northeast-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: ap-northeast-1a, ap-northeast-1c.

FYI, Its stack id is arn:aws:cloudformation:ap-northeast-1:073730675998:stack/Sample-ECS-ContinuousDeployment-VPC-YMS9BWIDVHQG/ff016890-3e8e-11e7-9079-50fa13f1d0ad

Thanks

**Comment by jpignata** [comment]
It appears that the `GetAZs` function is returning an AZ that are available to your account but currently does not permit subnets to be created. I'll dig into see if there's some kind of workaround though I suspect you'll have to parameterize or hardcode the available zones within a fork of the templates.

**Comment by tech-a-go-go** [comment]
Hi jpignata

Thank you for the info !

I will try it.

**Comment by jpignata** [comment]
Thanks! Let me know if that doesn't work for you.
