### ISSUE TITLE
IAM doc

### ISSUE THREAD

**Issue by matthewcummings** [awslabs/ecs-refarch-continuous-deployment#14]
It would be helpful if you documented which policies you need for the IAM role which you attach to this stack.  I ended up using the AdministratorAccess policy to just get this stack deployed and running.  Maybe that's necessary but it's not clear in the ReadMe.
Thanks!

Also, totally possible this is user error on my part.

**Comment by jpignata** [comment]
Oh, interesting. That's a good point. Will do!

**Comment by jpignata** [comment]
Sorry, I've not had time to assemble this list. If you have time and want to open a pull, that'd be much appreciated!
