### ISSUE TITLE
template files in ap-northeast-1

### ISSUE THREAD

**Issue by komushi** [awslabs/ecs-refarch-continuous-deployment#17]
Hi,

Thanks for the great material. We are from the ap-northeast-1 proserv.

SInce codebuild and codepipe are already available in ap-northeast-1 I was wondering if the templates files can be uploaded to the bucket in this region.

We would love to leverage this reference architecture with our customers. Having been asked by customers more and more regarding CICD and Container with managed services recently.

Thanks,
Lei Xu

**Comment by jpignata** [comment]
Hi Lei! I've made the change to the deploy files and I'll execute it on Tuesday when I'm back in the office. Sorry for the delay.

**Comment by jpignata** [comment]
I've deployed this to ap-northeast-1. Let me know if you have any issues.
