### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by frodeaa** [awslabs/ecs-refarch-continuous-deployment#18]
Great reference arch!

Some questions about it

 - where should other services (RDS, SQS etc) be added?
 - how will the service be affected by updates in infrastructure (ecs-cluster.yaml, load-balancer.yaml). Will changing cluster instance type mean downtime for the service?

**Comment by jpignata** [comment]
I don't think I have a strong opinion on other resources. I'd say that depending on their change rate, it might make sense to define them within the same template as your service. If they change at a faster or slower rate, perhaps a separate template with exported outputs.

If you were to change the underlying instance types, you'd be swapping out launch configurations. You can control how Auto Scaling manages this switcheroo -- see [here][asg-update].

[asg-update]: https://github.com/awslabs/ecs-refarch-continuous-deployment/blob/master/templates/ecs-cluster.yaml#L99
