### ISSUE TITLE
How to connect to a repo owned by a Github organization?

### ISSUE THREAD

**Issue by davidham** [awslabs/ecs-refarch-continuous-deployment#2]
Thanks so much for this project. I am trying to adapt it to a project at work, and I'm having trouble getting CodePipeline to read from a repo owned by my company's Github org. Is there an organization-level equivalent of the personal access token? If that needs to be an OAuth token, where do I find it?

**Comment by jpignata** [comment]
Hey @davidham - my understanding is that a personal access token should work for organization repos, too, assuming you are an admin for that organization and grant the token full permissions for repo and admin:repo_hook. Let me know if you find out differently.

**Comment by davidham** [comment]
Yup, must have been a different issue. Thanks!
