### ISSUE TITLE
no dockerfile

### ISSUE THREAD

**Issue by soydantaylor** [awslabs/ecs-refarch-continuous-deployment#22]
Is the intention that whoever consumes this example provide his/her own source code and dockerfile?  I understood that it was a working example that could be modified.

It doesn't work when it's first forked as there is no code to build nor is there a dockerfile

**Comment by dougtoppin** [comment]
Note that the first step is to fork their example repo into your GH account. That provides the Dockerfile that is later used. You are not actually using their repo but instead providing your own which is a copy.

**Comment by soydantaylor** [comment]
I did fork the repo, but I don't see a dockerfile.  I can provide my own.  That's no problem.  I'm just asking if that was the intention

**Comment by dougtoppin** [comment]
Make sure you are forking the example app repo (https://github.com/awslabs/ecs-demo-php-simple-app) and not the ref arch repo. The example app does have the Dockerfile.

**Comment by soydantaylor** [comment]
That was the issue.  Thank you
