### ISSUE TITLE
Intermixing JSON and YAML for Policies

### ISSUE THREAD

**Issue by maxwellimpact** [awslabs/ecs-refarch-continuous-deployment#23]
I noticed the use of JSON for the policies and I’m curious if this is an encouraged practice or what the advantage might be? My assumption is that it’s easier to copy and paste in from the web console. A few on our team were debating pure YAML or sticking with JSON for a policy. 

https://github.com/awslabs/ecs-refarch-continuous-deployment/blob/3c62bd5c69402556c8307f987f38a389c9064651/templates/service.yaml#L27

**Comment by jpignata** [comment]
That's a good point. This reference architecture was originally written in JSON, so I left the policies as JSON for expediency when I converted it. So, basically, I was lazy. My opinion is that pure YAML would be the better choice as I'd favor consistency if there's no benefit to the co-mingling. I'll likely update this in a future pass. Hope that helps!

**Comment by maxwellimpact** [comment]
@jpignata thanks for the response. makes sense!
