### ISSUE TITLE
Outdated S3 template file for service

### ISSUE THREAD

**Issue by elpasta** [awslabs/ecs-refarch-continuous-deployment#25]
Hello guys, there is a difference between the service template file in the S3 bucket referenced by the ecs-refarch-continuous-deployment.yaml file and the service template in the repo. The S3 bucket template file is looking for a Repsitory parameter you removed in the repo version. If you try to launch the stack you will get an error...

**Comment by jpignata** [comment]
Thanks! I apparently botched an aspect of the deploy. I've addressed this and just finished testing. Please let me know if you see any further issues.

**Comment by elpasta** [comment]
I will... thanks!
