### ISSUE TITLE
Updating a child stack directly can cause root stack to get stuck in UPDATE_ROLLBACK_FAILED

### ISSUE THREAD

**Issue by mathewpower** [awslabs/ecs-refarch-continuous-deployment#3]
It is very unadvisable to modify a child stack directly as this can cause the stack to get stuck in state which is hard to recover from.

If an update is being made to stack as a whole while a change is being made to a child stack and one fails, it can find it hard to roll back successfully. What tends to happen is a resource reports a status of being stable however another part of stack thinks its failed.

Generally when this happens a user is unable to fix it and it gets referred to the CloudFormation team which can take 12+ hours to resolve. 

Whenever I've spoken to the CF team they advice updating child stacks directly is not a good thing to do. 

In my opinion structuring your stacks in a way similar to that described in this example is a bad idea.

**Comment by jpignata** [comment]
Thanks! I'll look into this to see if the state issue you're referencing (an update happening within the main stack while a deployment is occurring, and a failure of either of those leaving the stack in a bad stack) has any mitigations or if we should restructure this.

Do you have any thoughts on a change to this reference architecture to mitigate this possibility?

**Comment by jpignata** [comment]
One thought I had is perhaps the pipeline should update the parent stack instead of reaching into the nested stack directly. This means we'd need to expose parameters like tag and desired count in the main stack and find a way to pass back in its other necessary parameters.

**Comment by mathewpower** [comment]
Changing the parent stack would be a good approach. I'm working on a project at the moment with a who load of microservices and we have come to the conclusion that having each service and each running task definition of that server (staging, production, etc) as their own stand alone stacks. 

We will have CodePipeline instantiate the stack to - ie when the pipeline reaches the production stage, if there is no stack in place it lets Cloud Formation create it. 

The way we are doing this is by having a stack which manages infrastructure and low(ish) level things like VPC, ALBs, ECS Cluster and exporting the outputs. Then we have a pipeline created for each service and then each task definition as separate, unrelated stacks.

This means we end up with groups of stacks which would give us the possibility to swap out the Code Pipeline stacks and replace them with Jenkins/TeamCity if one wishes to.... with a bit of work!

I'm going off a bit of a tangent here but it would be nice to have an example of a multi service, multi step, pipelines. Probably not within the scope of this example but I'd be happy to put up some examples when I get a chance.

**Comment by jpignata** [comment]
Thanks for the feedback. The approach you settled on seems right - the infrastructure and services have different change rates. The simplest change to make here might be to stop creating the service as a nested stack and let CodePipeline handle it on the first execution. I'll leave this issue open until I get a pull put together.

**Comment by mathewpower** [comment]
Sounds good. When I get a chance to get something together I'll pop a link on here to. Would be interested in getting your feedback as well!

**Comment by jpignata** [comment]
@mathewpower I still need to do another round of testing, but I opened https://github.com/awslabs/ecs-refarch-continuous-deployment/pull/4 for early review. Let me know if you have any comments.

**Comment by jpignata** [comment]
Closed in favor of https://github.com/awslabs/ecs-refarch-continuous-deployment/pull/4
