### ISSUE TITLE
Not able to create VPC

### ISSUE THREAD

**Issue by cueopsbot-cuelogic** [awslabs/ecs-refarch-continuous-deployment#32]
Getting below exception while launching stack in us-east-1 region.

![vpc_exception](https://user-images.githubusercontent.com/33514409/35267925-c9363fde-004d-11e8-9662-f92e99f98648.png)

**Comment by cueopsbot-cuelogic** [comment]
Managed to launch stack..I changed the vpc template and configured AZs that is supported for my account. Just wanted to know the default AZs this cloudformation stack uses to create VPC, subnets etc.?

**Comment by jpignata** [comment]
Hmm, I'm using the [`GetAzs`][getazs] intrinsic function to get Availability Zones that should work across users. From the docs:

> For the EC2-Classic platform, the Fn::GetAZs function returns all Availability Zones for a region. For the EC2-VPC platform, the Fn::GetAZs function returns only Availability Zones that have a default subnet unless none of the Availability Zones has a default subnet; in that case, all Availability Zones are returned.

Can you pass along the output of `aws ec2 describe-availability-zones` for the region in which you were trying to launch the template? Is it possible you have less than two default subnets?

Thanks!

[getazs]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html

**Comment by jpignata** [comment]
Closing for now - feel free to reach back out with more information so we can get to the root of the initial run's stack failure. Thanks!
