### ISSUE TITLE
Is AssignPublicIp required for Fargate?

### ISSUE THREAD

**Issue by zmingxie** [awslabs/ecs-refarch-continuous-deployment#35]
Hi there,

I'm new to ECS Fargate, and your template works great if I leave everything as default. However, I can't seem to bring up the Fargate task if I update this line to  `AssignPublicIp: DISABLED` https://github.com/awslabs/ecs-refarch-continuous-deployment/blob/master/templates/service.yaml#L66

From my understanding, ALB uses the VPC internal IP for forwarding traffic. Why do we have to  `AssignPublicIp` for the Fargate task? Or am I missing something else here?

Thanks!

**Comment by jpignata** [comment]
Hi! Fargate requires internet connectivity to pull the Docker image from ECR and to stream logs  to CloudWatch Logs. You don't need a public IP address necessarily - you could use a NAT Gateway or instance on a privats subnet instead. This reference architecture doesn't create that however so it does require `AssignPublicIp` to be `ENABLED`.

**Comment by zmingxie** [comment]
You are absolutely right! I kept thinking the issue is between ALB and the Fargate ENI and totally forgot about the needs for NAT. Thanks @jpignata!
