### ISSUE TITLE
What do I do here?  RocketShip is not intuitive... 

### ISSUE THREAD

**Issue by zipzit** [awslabs/ecs-refarch-continuous-deployment#37]
On the Running the Example, Step Number 2 Create the CloudFormation stack what to do isn't totally intuitive.  (I'm sitting in a class of folks who are this very minute going thru this example.)

![image](https://user-images.githubusercontent.com/4413134/37115138-29e2abec-21ff-11e8-9ea1-5661c5c04fe4.png)

`<a href="https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?stackName=ECS-ContinuousDeployment&amp;templateURL=https://s3.amazonaws.com/ecs-refarch-continuous-deployment/ecs-refarch-continuous-deployment.yaml&amp;param_LaunchType=Fargate" rel="nofollow"><g-emoji class="g-emoji" alias="rocket" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f680.png" ios-version="6.0">🚀</g-emoji></a>
`

(with perfect hindsight, the answer is to right click on the rocketship then chose open in new tab..., but that's not intuitive...)

Recommend that the Rocketship icon be displayed includes the words `click here 🚀`

Additionally recommend that `target="_blank" ` be added to those series of links....

**Comment by jpignata** [comment]
Sure! Thanks for the feedback. I'd happily merge a pull that includes the changes you've proposed. I previously used a "Launch" button - happy to also merge a pull that reverts to that.
